### ISSUE TITLE
Pylint throws exception for unexpected keyword argument when running prospector.

### ISSUE THREAD

**Issue by justke86** [PyCQA/prospector#266]
I was running prospector using python 3.6 and the latest version of prospector, but when attempting to run it, it would just throw the following error:
```
Traceback (most recent call last):
  File "<redacted>/bin/prospector", line 11, in <module>
    sys.exit(main())
  File "<redacted>/lib/python3.6/site-packages/prospector/run.py", line 173, in main
    prospector.execute()
  File "<redacted>/lib/python3.6/site-packages/prospector/run.py", line 53, in execute
    for tool in self.config.get_tools(found_files):
  File "<redacted>/python3.6/site-packages/prospector/config/__init__.py", line 45, in get_tools
    config_result = tool.configure(self, found_files)
  File "<redacted>/python3.6/site-packages/prospector/tools/pylint/__init__.py", line 185, in configure
    config_messages += self._pylintrc_configure(pylintrc, linter)
  File "<redacted>/lib/python3.6/site-packages/prospector/tools/pylint/__init__.py", line 103, in _pylintrc_configure
    are_plugins_loaded = linter.config_from_file(pylintrc)
  File "<redacted>/lib/python3.6/site-packages/prospector/tools/pylint/linter.py", line 24, in config_from_file
    self.read_config_file(config_file, quiet=True)
TypeError: read_config_file() got an unexpected keyword argument 'quiet'
```

From reading through the prospector codebase and the pylint codebase, it looks like the line `self.read_config_file(config_file, quiet=True)` is using the old keyword argument `quiet` prior to it being updated to be `verbose` instead within pylint.  This can be found in this commit: https://github.com/PyCQA/pylint/commit/49c6da5e7c90f7c53162fff1d8d9a2b6474ee28a#diff-ade2cfcf3e840a993dbd465f517d91f5.

**Comment by carlio** [comment]
Could you let me know what version of prospector + pylint you are running with a pip freeze? I think I fixed that in this commit just yesterday for version 1.0 - https://github.com/PyCQA/prospector/commit/13214a0ff0dde10cc5194d0b6b0685fbcab2a3b9

You will have to upgrade prospector and pylint.

**Comment by justke86** [comment]
I'm currently using pipenv 2018.7.1, and here's the pipenv graph when running into this issue:
```
14:03 $ pipenv graph
prospector==1.0
  - dodgy [required: >=0.1.9, installed: 0.1.9]
  - mccabe [required: >=0.5.0, installed: 0.6.1]
  - pep8-naming [required: >=0.3.3, installed: 0.7.0]
    - flake8-polyfill [required: >=1.0.2,<2, installed: 1.0.2]
      - flake8 [required: Any, installed: 3.5.0]
        - mccabe [required: >=0.6.0,<0.7.0, installed: 0.6.1]
        - pycodestyle [required: >=2.0.0,<2.4.0, installed: 2.3.1]
        - pyflakes [required: >=1.5.0,<1.7.0, installed: 1.6.0]
  - pycodestyle [required: >=2.0.0,<2.4.0, installed: 2.3.1]
  - pydocstyle [required: >=2.0.0, installed: 2.1.1]
    - six [required: Any, installed: 1.11.0]
    - snowballstemmer [required: Any, installed: 1.2.1]
  - pyflakes [required: >=0.8.1,<2.0.0, installed: 1.6.0]
  - pylint [required: >=2, installed: 2.0.1]
    - astroid [required: >=2.0.1, installed: 2.0.1]
      - lazy-object-proxy [required: Any, installed: 1.3.1]
      - six [required: Any, installed: 1.11.0]
      - typed-ast [required: Any, installed: 1.1.0]
      - wrapt [required: Any, installed: 1.10.11]
    - isort [required: >=4.2.5, installed: 4.3.4]
    - mccabe [required: Any, installed: 0.6.1]
  - pylint-common [required: >=0.2.5, installed: 0.2.5]
    - pylint [required: >=1.0, installed: 2.0.1]
      - astroid [required: >=2.0.1, installed: 2.0.1]
        - lazy-object-proxy [required: Any, installed: 1.3.1]
        - six [required: Any, installed: 1.11.0]
        - typed-ast [required: Any, installed: 1.1.0]
        - wrapt [required: Any, installed: 1.10.11]
      - isort [required: >=4.2.5, installed: 4.3.4]
      - mccabe [required: Any, installed: 0.6.1]
    - pylint-plugin-utils [required: >=0.2.5, installed: 0.4]
      - pylint [required: Any, installed: 2.0.1]
        - astroid [required: >=2.0.1, installed: 2.0.1]
          - lazy-object-proxy [required: Any, installed: 1.3.1]
          - six [required: Any, installed: 1.11.0]
          - typed-ast [required: Any, installed: 1.1.0]
          - wrapt [required: Any, installed: 1.10.11]
        - isort [required: >=4.2.5, installed: 4.3.4]
        - mccabe [required: Any, installed: 0.6.1]
  - pylint-plugin-utils [required: >=0.2.6, installed: 0.4]
    - pylint [required: Any, installed: 2.0.1]
      - astroid [required: >=2.0.1, installed: 2.0.1]
        - lazy-object-proxy [required: Any, installed: 1.3.1]
        - six [required: Any, installed: 1.11.0]
        - typed-ast [required: Any, installed: 1.1.0]
        - wrapt [required: Any, installed: 1.10.11]
      - isort [required: >=4.2.5, installed: 4.3.4]
      - mccabe [required: Any, installed: 0.6.1]
  - pyyaml [required: Any, installed: 3.13]
  - requirements-detector [required: >=0.6, installed: 0.6]
    - astroid [required: >=1.4, installed: 2.0.1]
      - lazy-object-proxy [required: Any, installed: 1.3.1]
      - six [required: Any, installed: 1.11.0]
      - typed-ast [required: Any, installed: 1.1.0]
      - wrapt [required: Any, installed: 1.10.11]
  - setoptconf [required: >=0.2.0, installed: 0.2.0]
```

Here's the pip freeze info from within the virtual env:
```
astroid==2.0.1
dodgy==0.1.9
flake8==3.5.0
flake8-polyfill==1.0.2
isort==4.3.4
lazy-object-proxy==1.3.1
mccabe==0.6.1
pep8-naming==0.7.0
prospector==1.0
pycodestyle==2.3.1
pydocstyle==2.1.1
pyflakes==1.6.0
pylint==2.0.1
pylint-common==0.2.5
pylint-plugin-utils==0.4
PyYAML==3.13
requirements-detector==0.6
setoptconf==0.2.0
six==1.11.0
snowballstemmer==1.2.1
typed-ast==1.1.0
wrapt==1.10.11
```

I'm using python 3.6.3 and I think I have the latest pylint and prospector.

**Comment by carlio** [comment]
Seems I must have misread the change when the `quiet` flag moved around. Thanks for pointing this out - I'll get on it ASAP.

**Comment by justke86** [comment]
Looking at the commit you sent, should the `quiet=True` be in the else block there?

**Comment by carlio** [comment]
Before pylint 2, it was called quiet but used in a different method ; I tried to make it work with old and new versions but missed that it was renamed in newer versions. Sorry about that.

**Comment by justke86** [comment]
No problem, it happens, just figured I'd point it out so others don't run into similar issues, although from looking at your commit that you posted above, it looks like you may just need to move the `quiet=True` to the `else` block, right?  I didn't dig deep enough into where you're setting `PYLINT_VERSION` to confirm though.

**Comment by carlio** [comment]
You're welcome to make a PR ;-)  I probably can't get on to this until tomorrow.

PYLINT_VERSION is just loaded from `pylint.__pckinfo__` so it's the exact same version that pylint uses in its setup.py.

**Comment by justke86** [comment]
That's understandable, I was a little hesitant at first on the PR, but I gave it a shot: https://github.com/PyCQA/prospector/pull/267

**Comment by justke86** [comment]
Is there any update on this issue?

**Comment by chocoelho** [comment]
Keeping this issue open until the fix is released.

**Comment by Doatti** [comment]
I still have this problem on prospector 1.1.2. Also using virtualenv. Here's my traceback:

```
Traceback (most recent call last):
  File "<redacted>/bin/prospector", line 11, in <module>
    load_entry_point('prospector==1.1.2', 'console_scripts', 'prospector')()
  File "<redacted>/local/lib/python2.7/site-packages/prospector/run.py", line 173, in main
    prospector.execute()
  File "<redacted>/local/lib/python2.7/site-packages/prospector/run.py", line 53, in execute
    for tool in self.config.get_tools(found_files):
  File "<redacted>/local/lib/python2.7/site-packages/prospector/config/__init__.py", line 41, in get_tools
    config_result = tool.configure(self, found_files)
  File "<redacted>/local/lib/python2.7/site-packages/prospector/tools/pylint/__init__.py", line 184, in configure
    config_messages += self._pylintrc_configure(pylintrc, linter)
  File "<redacted>/local/lib/python2.7/site-packages/prospector/tools/pylint/__init__.py", line 102, in _pylintrc_configure
    are_plugins_loaded = linter.config_from_file(pylintrc)
  File "<redacted>/local/lib/python2.7/site-packages/prospector/tools/pylint/linter.py", line 26, in config_from_file
    self.read_config_file(config_file, quiet=True)
TypeError: read_config_file() got an unexpected keyword argument 'quiet'
```

**Comment by kpachnis** [comment]
Pull request #283 solves this issue. 

Looking at the PyLint history, the `quiet` argument never existed, at least from PyLint 1.5 onward, but is was an instance variable of class OptionsManagerMixIn. In version 2.0.1 was remove completely.

**Comment by ltalirz** [comment]
@chocoelho Why did you close this issue?
The issue persists (cannot use prospector with pylint <2), and there is a PR open (#283) to resolve it.
I checked and confirm that this PR resolves the issue.

Please consider merging #283 and releasing a new version of prospector.

**Comment by chocoelho** [comment]
I may have closed it by mistake, will merge some PRs today and release a
new prospector version later today.

Em quinta-feira, 15 de novembro de 2018, Leopold Talirz <
notifications@github.com> escreveu:

**Comment by ltalirz** [comment]
@chocoelho Thanks a lot, works for me!
From my side the issue can be closed.
