### ISSUE TITLE
Running pre-commit outputs error multiple times

### ISSUE THREAD

**Issue by C0DK** [PyCQA/prospector#341]
I am trying to use the pre-commit hook you show in your readme, however for some reason the output is outputted multiple times:

```
prospector...............................................................Failed
Messages
========

.
  Line: None
    pylint: failure / Tool pylint failed to run (exception was raised)

accounts/tests.py
  Line: 2
    pyflakes: F401 / 'decimal.Decimal' imported but unused (col 1)

accounts/views.py
  Line: 343
    mccabe: MC0001 / details is too complex (23)



Check Information
=================
         Started: 2019-07-14 12:20:14.736918
        Finished: 2019-07-14 12:20:20.620338
      Time Taken: 5.88 seconds
       Formatter: grouped
        Profiles: .prospector.yaml, full_pep8, strictness_veryhigh, no_doc_warnings, no_member_warnings, no_test_warnings
      Strictness: from profile
  Libraries Used: django
       Tools Run: dodgy, mccabe, pep8, profile-validator, pyflakes, pylint
  Messages Found: 3

Messages
========

.
  Line: None
    pylint: failure / Tool pylint failed to run (exception was raised)

accounts/customer_views.py
  Line: 14
    pyflakes: F401 / 'communication.automation.send_signup_information_received_email' imported but unused (col 1)

accounts/models.py
  Line: 482
    pyflakes: F999 / 'raise NotImplemented' should be 'raise NotImplementedError' (col 9)

investorsuite/settings.py
  Line: 32
    dodgy: secret / Possible hardcoded secret key



Check Information
=================
         Started: 2019-07-14 12:20:14.658991
        Finished: 2019-07-14 12:20:18.784852
      Time Taken: 4.13 seconds
       Formatter: grouped
        Profiles: .prospector.yaml, full_pep8, strictness_veryhigh, no_doc_warnings, no_member_warnings, no_test_warnings
      Strictness: from profile
  Libraries Used: django
       Tools Run: dodgy, mccabe, pep8, profile-validator, pyflakes, pylint
  Messages Found: 4

Messages
========
```

which is weird. Not sure if it is on your end or theirs, but it only happens with prospector.

I have the following pre-commit-config:
```
fail_fast: true
repos:
-   repo: https://github.com/PyCQA/prospector
    rev: 1.1.6.4 # The version of Prospector to use, at least 1.1.6
    hooks:
    -   id: prospector
```

I only have the problem with the pre-commit, not running the prospector program directly.

**Comment by chocoelho** [comment]
`1.1.6.3` and `1.1.6.4` are versions there we're currently facing issues. `1.1.7` will solve that, and to reach it  we made a pre-release version: `1.1.7.dev0` which is being reported as working properly again with updated pylint versions.

**Comment by C0DK** [comment]
Awesome. I'm glad to hear. You are truly doing an amazing job with both this an other packages at the PyCQA. Currently i don't seem to be able to find `1.1.7.dev0` via pre-commit nor plain ol' github, but I'll simply way a few weeks for the new release. In the meantime, if you have issues i could help with, then please reach out to me. I have some years of python experience, but i'm probably still a noob compared to you guys.

**Comment by chocoelho** [comment]
Hey @C0DK, I noticed I forgot to create a tag here for this release, so I just did it :) sorry about that. We always welcome PRs and contributions. One thing that is always requested in prospector is keeping up-to-date with the tools it depends on, but as we pin these dependencies due to them breaking compatibility from time to time, it takes some time to update them. This is one place to start with if you want to start contributing with code :D

**Comment by chocoelho** [comment]
Closing this as prospector 1.1.7 should fix this issue. Feel free to reopen it if this is erroring for you.

**Comment by C0DK** [comment]
currently running with:
```
-   repo: https://github.com/PyCQA/prospector
    rev: 1.1.7.dev0
    hooks:
    -   id: prospector
```

And still getting duplicate responses. i can try looking into it myself though and give a more detailed bug report and or a PR

**Comment by chocoelho** [comment]
@C0DK is this still happening with stable `1.1.7`? For duplicates, it should be another issue, how do you feel about contribute with suggestions for `prospector\blender_combinations.yaml`? 😃

**Comment by C0DK** [comment]
Yep. using `rev: 1.1.7` now. This is the (shortened) output. please ignore my low linting score :cry: 

```
....


Check Information
=================
         Started: 2019-07-30 13:16:34.607779
        Finished: 2019-07-30 13:17:08.938005
      Time Taken: 34.33 seconds
       Formatter: grouped
        Profiles: .prospector.yaml, full_pep8, strictness_veryhigh, no_doc_warnings, no_member_warnings, no_test_warnings
      Strictness: from profile
  Libraries Used: django
       Tools Run: dodgy, mccabe, pep8, profile-validator, pyflakes, pylint
  Messages Found: 61

Messages
========

.....

Check Information
=================
         Started: 2019-07-30 13:16:34.956252
        Finished: 2019-07-30 13:17:12.485295
      Time Taken: 37.53 seconds
       Formatter: grouped
        Profiles: .prospector.yaml, full_pep8, strictness_veryhigh, no_doc_warnings, no_member_warnings, no_test_warnings
      Strictness: from profile
  Libraries Used: django
       Tools Run: dodgy, mccabe, pep8, profile-validator, pyflakes, pylint
  Messages Found: 72

Messages
========


.......


Check Information
=================
         Started: 2019-07-30 13:16:34.595126
        Finished: 2019-07-30 13:17:10.091255
      Time Taken: 35.50 seconds
       Formatter: grouped
        Profiles: .prospector.yaml, full_pep8, strictness_veryhigh, no_doc_warnings, no_member_warnings, no_test_warnings
      Strictness: from profile
  Libraries Used: django
       Tools Run: dodgy, mccabe, pep8, profile-validator, pyflakes, pylint
  Messages Found: 51
```

Not sure how pre-commit passes the files into prospector, but it seems like it's different files each time the prospector is run (as the messages found each time differs). it seems like it is run multiple times, or something. So it seems like there is an issue with the integration between the two services, in some way.

my complete current file is as follows:
```repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: check-merge-conflict
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
      args:
      - --line-length=100
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: check-added-large-files
    -   id: check-ast
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer
    -   id: flake8
        args:
        - --max-line-length=101
        - --exclude=*/migrations/*,docs/*
        - --ignore=E126,W503
# TODO use prospector instead of flake8 etc
-   repo: https://github.com/PyCQA/prospector
    rev: 1.1.7 # The version of Prospector to use, at least 1.1.6
    hooks:
    -   id: prospector

```


Regarding contributing, just to understand you correctly, are you asking for additions to the list, or what? :smile: gladly, but i am not sure where to sniff those out.

**Comment by chocoelho** [comment]
Aaah, got the real problem. At first, I'd advise you to use `prospector -M` to output messages only, so no summary will be shown, but the repetition is definitely something we'll check into it. Can you file another issue for that?

**Comment by C0DK** [comment]
i mean that was what i meant by this error originally, however I migt have phrased myself badly.

**Comment by chocoelho** [comment]
@C0DK yeah, it was me being dumb. I reopened the issue as I understood the problem was another thing.

**Comment by laundmo** [comment]
any updates on this? would love to use prospector in my pre-commits but the duplicated output is just really annoying.

**Comment by carlio** [comment]
I think this is fixed - the problem was that it was running `for file in files: prospector file` because it was not running in serial mode.

I've added that to the pre-commit hook configuration - https://github.com/PyCQA/prospector/blob/master/.pre-commit-hooks.yaml#L7

So if you try now, it should not have these duplicates of the summary.
